services:
  mysql-write:
    networks:
      - ballcom
    image: mysql:latest
    container_name: mysql-write
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ballcom
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
    ports:
      - 3307:3306
    volumes:
      - mysql-write:/var/lib/mysql

  mysql-read:
    networks:
      - ballcom
    image: mysql:latest
    container_name: mysql-read
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ballcom
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
    ports:
      - 3306:3306
    volumes:
      - mysql-read:/var/lib/mysql

  rabbitmq:
    networks:
      - ballcom
    image: rabbitmq:3.7-management
    container_name: rabbitmq-queue
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  eventstoredb:
    networks:
      - ballcom
    image: eventstore/eventstore:latest
    container_name: eventstoredb
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    command: --insecure
    volumes:
      - eventstore-data:/data/db

  order-service:
    networks:
      - ballcom
    build: ./order-management
    container_name: order-service
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql-write
      - mysql-read
      - rabbitmq
      - eventstoredb
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql-write
      MYSQL_PORT: 3306
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
      MYSQL_DATABASE: ballcom
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  inventory-service:
    networks:
      - ballcom
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    container_name: inventory-service
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysql-write
      - mysql-read
      - rabbitmq
    environment:
      MYSQL_HOST: mysql-write
      MYSQL_PORT: 3306
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
      MYSQL_DATABASE: ballcom
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  invoice-service:
    networks:
     - ballcom
    build:
     context: .
     dockerfile: ./invoice-service/Dockerfile
    container_name: invoice-service
    restart: always
    ports:
     - 5000:5000
    depends_on:
      - mysql-write
      - mysql-read
      - rabbitmq
    environment:
      MYSQL_HOST: mysql-write
      MYSQL_PORT: 3306
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
      MYSQL_DATABASE: ballcom
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  customer-service:
    networks:
     - ballcom
    build:
     context: .
     dockerfile: ./customer-service/customer-service/Dockerfile
    container_name: customer-service
    restart: always
    ports:
     - 8080:8080
     - 8081:8181
    depends_on:
      - mysql-write
      - mysql-read
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: server=mysql-write;port=3306;database=ballcom;user=administrator;password=password420;
      MYSQL_HOST: mysql-write
      MYSQL_PORT: 3306
      MYSQL_USER: administrator
      MYSQL_PASSWORD: password420
      MYSQL_DATABASE: ballcom
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest


volumes:
  mysql-write:
  mysql-read:
  rabbitmq-data:
  eventstore-data:

networks:
  ballcom:
    driver: bridge
